### ISSUE TITLE
переход на mui v5

### ISSUE THREAD

**Issue by MaxGorshkov** [SoftMediaLab/materialui-table#13]
- [x] 1. обновить зависимости:
@material-ui/core -> @mui/material
@material-ui/icons -> @mui/icons-material

- [x] 2. выполнить измененения согласно [инструкции](https://mui.com/guides/migration-v4/) по миграции mui с v4 на v5;

- [x] 3. заменить библиотеку [@material-ui/pickers](https://github.com/mui-org/material-ui-pickers) на родной [mui datepicker](https://mui.com/components/date-picker/);

- [x] 4. проверить работоспособность демонстрационной страницы (доступна после выполнения npm start по адресу http://localhost:8080/). Особое внимание уделить проверке datepicker.

**Comment by sashahohloma** [comment]
При переходе на mui v5 возникли критические ошибки:

- [x] При инициализации таблицы в компоненте OutlinedInput возникает ошибка: `undefined is not an object (evaluating 'theme.palette[ownerState.color].main')`
- [x] При переключении параметра FilterRow в положение Row возникает ошибка: `undefined is not an object (evaluating '_this2.props.icons')`
- [x] При клике на поле фильтрации даты возникает ошибка: `utils.getYearText is not a function. (In 'utils.getYearText(date)', 'utils.getYearText' is undefined)`
- [x] При клике на значок редактирования в строке возникает ошибка:  `Format string contains an unescaped latin alphabet character `n``
