### ISSUE TITLE
Добавить возможность бесконечного скролла

### ISSUE THREAD

**Issue by sashahohloma** [SoftMediaLab/materialui-table#8]
Необходимо добавить следующие props:

- [ ] height (высота видимой части контента таблицы) для расчёта нижней границы скролла
- [ ] startPage для сброса параметра page при возможной смене параметров запроса к внешним ресурсам
- [ ] hasMore, либо limit чтобы остановить бесконечный скролл
- [ ] threshold для указания порога срабатывания onEndScroll
- [ ] onEndScroll для вызова внешней функции обновления данных. В качестве аргумента функции передавать параметр page. При каждом вызов функции значение page инкрементируется

**Comment by sashahohloma** [comment]
**Полезные ссылки**

[react-infinite-scroll-component](https://www.npmjs.com/package/react-infinite-scroll-component)

**Comment by MaxGorshkov** [comment]
я предлагаю не переусложнять интерфейс, а оттолкнуться от существующего [механизма подгрузки данных с сервера](https://material-table.com/#/docs/features/remote-data)

**Comment by MaxGorshkov** [comment]
модифицируем paging (boolean) в pagingMode (enum 'classic' | 'scroll' | 'disabled'), новых свойств не добавляем, threshold хардкодим динамическим типлом в зависимости от высоты области для вывода строк (TableBody)
